fix upd_progress
This commit imports debian patch "70_fix_upd_progress.patch".

Fix the --upd-progress function which dies with the following
traceback.  Debian #351453

> 11510:tbm@derision: ~/tmp/jack/jack-1210f412] jack --upd-progress
> This is jack 3.1.1 (C)2004 Arne Zellentin <zarne@users.sf.net>
> Traceback (most recent call last):
>   File "/usr/bin/jack", line 136, in ?
>     jack_prepare.update_progress(todo)
>   File "/usr/lib/python2.3/site-packages/jack_prepare.py", line 341, in update_progress
>     if not status[num]['dae']:
> NameError: global name 'status' is not defined

(and when this is fixed, dies because the ogg modules is not loaded)

Depends on 33_flac_mutagen.patch